IPScanner
atc-net/atc-network pull request #10
Opened 2022-08-12 10:23 UTC by davidkallesen

- Add IPScanner

2022-08-12 12:03 UTC, lupusbytes requested changes

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Enums/IPScannerProgressReportingType.cs
> +    IpAddressStart,
Capitalize IP
`IPAddressStart, IPAddressDone`
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers
- A special case is made for two-letter acronyms in which both letters are capitalized, as shown in the following identifier:

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +            return (false, "Start-IP-address is not v4");
`$"nameof(startIpAddress) is not IPv4"`
I have never heard anyone refer to the version just as v4 or v6. It's always IPv4 or IPv6

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +            return (false, "End-IP-address is not v4");
same as above

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +        var ipS = BitConverter.ToUInt32(startIpAddressAsBytes);
i don't like these variable names, `ipS`, `ipE`

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +        return ipS > ipE
This could be simplified to 
`BitConverter.ToUInt32(startIpAddress.GetAddressBytes()) > BitConverter.ToUInt32(endIpAddress.GetAddressBytes()) ? ... `

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +            ? (false, "Expect Start-IP-address is greater then End-IP-address")
Why "Expect"?
 `$"{nameof(startIpAddress)} is higher than {nameof(endIpAddress)}"`

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +        string cidrMask)
this is a CIDR notation, not a mask

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Helpers/PingHelper.cs
> +        int timeoutInMs = 1000)
Use `TimeSpan` instead of int for timeout ? 
or maybe an overload that converts between the two.

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Internet/IPScanner.cs
> +        int cidrMaskLength,
rename to `cidrMaskLength` to `cidrLength` or `cidr`.
"Mask" usually refers to a subnet mask, like 255.255.255.0, not a number.
use `byte` for cidrLength.

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Enums/IPProtocolType.cs
> +    None,
Wouldn't it make sense to assign the default port numbers to these values?
Example: 

```
Http = 80,
Https = 443
```

2022-08-12 12:03 UTC, lupusbytes commented on src/Atc.Network/Enums/IPProtocolType.cs
> +    None,
How is TCP in the same category as HTTP ?

2022-08-12 16:08 UTC, lupusbytes requested changes

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +    public static IPAddress[] GetAddressesInRange(
Why does this have to be an array?. Wouldn't a more generic return type like `IReadOnlyCollection<IPAddress>` be better ?

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +    public static IPAddress[] GetAddressesInRange(
Why does this have to be an array?. Wouldn't a more generic return type like `IReadOnlyCollection<IPAddress>` be better ?

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +    public static (IPAddress StartIpAddress, IPAddress EndIpAddress) GetStartAndEndAddressesInRange(
I think I would like `GetFirstAndLastIPAddressInRange` as a method name better

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/KnowTcpUdpPortsLookupHelper.cs
> +/// KnowIPPortsLookupHelper.
What kind of summary is this ? ;)

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/KnowTcpUdpPortsLookupHelper.cs
> +public static class KnowTcpUdpPortsLookupHelper
Know -> Known

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/KnowTcpUdpPortsLookupHelper.cs
> +public static class KnowTcpUdpPortsLookupHelper
Maybe WellKnown ? But you included alot of guesses/assumptions like port 581 for HTTP. So one could argue that this is more of a GuessPortsHelper ...

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/IPAddressV4Helper.cs
> +public static class IPAddressV4Helper
Sounds much better as IPv4AddressHelper

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Helpers/KnowTcpUdpPortsLookupHelper.cs
> +    private static readonly List<int> Https = new()
The maximum port number is 65535 which is 16 bits and can be accurately represented as an ushort.

2022-08-12 16:08 UTC, lupusbytes commented on src/Atc.Network/Models/IPScanResult.cs
> +        IPAddress iPAddress)
iPAddress -> ipAddress

2022-08-12 16:08 UTC, lupusbytes commented on test/Atc.Network.Test/Extensions/IPScannerConfigExtensionsTests.cs
> +            ResolveServiceProtocolHttp = resolveIPProtocolHttp,
in all other places in this code, we're not following the convention of capitalizing two letter accronyms when writing camelcase. so resolveIPProtocolHttp -> resolveIpProtocolHttp

2022-08-12 18:27 UTC, lupusbytes commented on src/Atc.Network/Internet/IPScanner.cs
> +        int cidrMaskLength,
we would still need to check that the cidrLength is 32 or less. 
a `byte` is a unsigned 8-bit integer which can have a value of 0-255

2022-08-15 10:35 UTC, perkops approved these changes, later dismissed

2022-08-15 10:40 UTC, perkops approved these changes

2022-08-15 10:50 UTC, merged